/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package local.pkovalev.adventofcode.aoc2024;

import local.pkovalev.adventofcode.aoc2024.days.*;
import lombok.extern.slf4j.Slf4j;

import java.time.Instant;

@Slf4j
public class App
{
    public static void main( String[] args )
    {
        var timeStart = Instant.now();
        DayInterface day = new Day1_1();
        var result = day.solveRiddle();
        var timeEnd = Instant.now();
        var interval = timeEnd.toEpochMilli() - timeStart.toEpochMilli();
        log.info("Done in {}.{} seconds", interval / 1000, String.format("%03d", interval % 1000));
        log.info("Result: [{}]", result);
    }
}

